$("img1").explode({
  omitLastLine = false,
  radius =80,
  minradius =20,
  release =true,
  fadeTime = 300,
  recycle =true,
  recycleDelay = 500,
  fill = true,
  explodeTime =300,
  maxAngle =360,
  gravity =0,
  round =false,
  groundDistance = 400,
  ignoreComplete = false,
  land =true,
  checkOutBound,
  finish,
});